twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        option_service: '@App\Service\OptionService'
    

when@test:
    twig:
        strict_variables: true
